-- SQL скрипт для создания таблиц вручную (без миграций)
-- Выполните этот скрипт в pgAdmin 4 Query Tool

-- Создание таблицы Users
CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(50) NOT NULL,
    "PhoneNumber" text NOT NULL,
    "PasswordHash" character varying(100) NOT NULL,
    "IsAdmin" boolean NOT NULL
);

-- Создание таблицы Workouts
CREATE TABLE IF NOT EXISTS "Workouts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Trainer" text NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone NOT NULL,
    "Slug" character varying(100) NOT NULL,
    "VideoUrl" text
);

-- Создание таблицы PurchasedWorkouts
CREATE TABLE IF NOT EXISTS "PurchasedWorkouts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "WorkoutId" integer NOT NULL,
    "PurchaseDate" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_PurchasedWorkouts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PurchasedWorkouts_Workouts_WorkoutId" FOREIGN KEY ("WorkoutId") REFERENCES "Workouts" ("Id") ON DELETE CASCADE
);

-- Создание индексов
CREATE INDEX IF NOT EXISTS "IX_PurchasedWorkouts_UserId" ON "PurchasedWorkouts" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_PurchasedWorkouts_WorkoutId" ON "PurchasedWorkouts" ("WorkoutId");

-- Добавление администратора (если его еще нет)
INSERT INTO "Users" ("Id", "Name", "PhoneNumber", "PasswordHash", "IsAdmin")
VALUES (1, 'Admin', '77777777777', '/Pe7bVRs+4LS5VSGmErnoYYqZmrLRB4M+LTtNKT8+dc=', true)
ON CONFLICT ("Id") DO NOTHING;

-- Обновление последовательности для Users
SELECT setval('"Users_Id_seq"', (SELECT MAX("Id") FROM "Users") + 1, false);

-- Проверка: какие таблицы созданы
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_type = 'BASE TABLE'
ORDER BY table_name;

